-- 1. 부서 테이블
CREATE TABLE TB_DEPT (
    DEPT_ID     INT AUTO_INCREMENT PRIMARY KEY,
    DEPT_NAME   VARCHAR(100) NOT NULL,
    CREATE_DT   DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT   DATETIME ON UPDATE CURRENT_TIMESTAMP
);

-- 2. 직원 테이블 (암호 수정일, 삭제/사용/탈퇴 여부 포함)
CREATE TABLE TB_EMP (
    EMP_ID        VARCHAR(50) PRIMARY KEY,
    EMP_NAME      VARCHAR(50) NOT NULL,
    ROLES         ENUM('master', 'admin', 'leader', 'team', 'user') DEFAULT 'user',
    PASSWORD      VARCHAR(255) NOT NULL,
    DESCRIPTION   TEXT,
    PWD_CHG_DT    DATETIME,              -- 암호 수정일
    USE_YN        CHAR(1) DEFAULT 'Y',   -- 사용여부
    DEL_YN        CHAR(1) DEFAULT 'N',   -- 삭제여부
    EXIT_YN       CHAR(1) DEFAULT 'N',   -- 탈퇴여부
    EXIT_DT       DATETIME,              -- 탈퇴날짜
    UPPER_EMP_ID  VARCHAR(50),           -- 상급자 아이디
    DEPT_ID       INT,                   -- 소속 부서
    CREATE_DT     DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT     DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UPPER_EMP_ID) REFERENCES TB_EMP(EMP_ID),
    FOREIGN KEY (DEPT_ID) REFERENCES TB_DEPT(DEPT_ID)
);

-- 3. 직원 로그 테이블 (제공해주신 스펙 100% 반영)
CREATE TABLE EMP_LOG (
    LOG_ID       VARCHAR(50) CHARACTER SET utf8 NOT NULL PRIMARY KEY,
    EMP_ID       VARCHAR(50) CHARACTER SET utf8 NOT NULL,
    EMP_NAME     VARCHAR(50) CHARACTER SET utf8 NULL,
    IP           VARCHAR(50) CHARACTER SET utf8 NULL,
    CITY         VARCHAR(50) CHARACTER SET utf8 NULL,
    REGION       VARCHAR(50) CHARACTER SET utf8 NULL,
    COUNTRY      VARCHAR(50) CHARACTER SET utf8 NULL,
    LOC          VARCHAR(50) CHARACTER SET utf8 NULL,
    ORG          VARCHAR(50) CHARACTER SET utf8 NULL,
    POSTAL       VARCHAR(50) CHARACTER SET utf8 NULL,
    TIMEZONE     VARCHAR(50) CHARACTER SET utf8 NULL,
    LOGIN_TIME   VARCHAR(50) CHARACTER SET utf8 NULL,
    LOGOUT_TIME  VARCHAR(50) CHARACTER SET utf8 NULL,
    BROWSER_NAME VARCHAR(50) CHARACTER SET utf8 NULL,
    OS_NAME      VARCHAR(50) CHARACTER SET utf8 NULL,
    DEVICE_NAME  VARCHAR(50) CHARACTER SET utf8 NULL,
    MEMO         VARCHAR(100)             NULL
) COLLATE = armscii8_bin;